import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={"bg-gray-400"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Welcome to learning Hulu movie app...!
      </div>

    </div>
  )
}
